---
version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.3
    command: ["logstash", "-f", "pipeline/first-pipeline.conf", "--config.reload.automatic"]
    ports:
      - "5044:5044"
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/
      - ./:/repo/:ro

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.3
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./:/repo/:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      ELASTIC_PASSWORD: "password"
      "discovery.type": "single-node"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    environment:
      ELASTICSEARCH_PASSWORD: "password"
    ports:
      - "5601:5601"
